services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
